<template>
  <div class="report">
    <header class="logo">
      <img src="/logo-black.png" alt="">
    </header>
    <div class="content">
      <h1>Valkyrie2544 Test Report</h1>
      <div class="part">
        <h2>Test Summary</h2>
        <div class="fields">
          <div>Test company:</div>
          <div>Xena Networks</div>
        </div>
        <div class="fields">
          <div>Customer:</div>
          <div>Xena Networks</div>
        </div>
        <div  class="fields">
          <div>Test Date and Time:</div>
          <div>2022-01-06, 10:37</div>
        </div>
        <div  class="fields">
          <div>Test Duration:</div>
          <div>00:00:32 (h:m:s)</div>
        </div>
        <div  class="fields">
          <div>Generated By:</div>
          <div>Valkyrie2544 v2.83, running on 'Microsoft Windows 10 Home China'</div>
        </div>
      </div>

      <div class="part">
        <h2>Test Setup</h2>
        <h3>Test Configuration</h3>
        <h4>Main Test Options</h4>
        <div  class="fields">
          <div>Frame Size Type:</div>
          <div>Custom Sizes</div>
        </div>
        <div class="fields">
          <div>Frame Size used:</div>
          <div>512</div>
        </div>

        <h3>Port Configuration</h3>
        <div class="fields">
          <div>Used Port Count:</div>
          <div>2</div>
        </div>

        <h4>Used Chassis Summary</h4>
        <table class="gridtable">
          <thead>
            <tr>
              <th>Chassis ID</th>
              <th>Chassis Name</th>
              <th>Chassis Serial#</th>
              <th>Address and Port</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>C-0</td>
              <td>New Chassis</td>
              <td>11144099</td>
              <td>192.168.1.198:22606</td>
            </tr>
          </tbody>
        </table>

        <h4>Port Traffic Setup</h4>
        <table class="gridtable">
          <thead>
            <tr>
              <th>Port ID</th>
              <th>IP Address & Gateway</th>
              <th>Protocol Segment Profile</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>P-0-0-2</td>
              <td>No address specified </td>
              <td>1: Ethernet</td>
            </tr>
            <tr>
              <td>P-0-0-3</td>
              <td>No address specified </td>
              <td>1: Ethernet</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="part">
        <h2>Frame Loss Rate Test Results</h2>
        <h3>Test Setup</h3>
        <div>
          <div>Time Duration:</div>
          <div>1 Seconds</div>
        </div>
        <div>
          <div>Iterations: </div>
          <div>1</div>
        </div>
        <div>
          <div>Use Pass/Fail Criteria:</div>
          <div>No</div>
        </div>

        <h3>Test Results</h3>
        <h4>Results for 50.00% Rate</h4>
        <table class="gridtable">
          <thead>
            <tr>
              <th>Frame Size</th>
              <th>512</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Result State</td>
              <td>PASS</td>
            </tr>
            <tr>
              <td>Tx (Frames)</td>
              <td>234,962</td>
            </tr>
            <tr>
              <td>Tx Rate (Fps)</td>
              <td>234,962</td>
            </tr>
            <tr>
              <td>Tx Rate (L1) (Bit/s)</td>
              <td>1000 M</td>
            </tr>
            <tr>
              <td>Rx (Frames)</td>
              <td>234,962</td>
            </tr>
            <tr>
              <td>Rx Rate (Fps)</td>
              <td>234.96 K</td>
            </tr>
            <tr>
              <td>Rx Rate (L1) (Bit/s)</td>
              <td>1000 M</td>
            </tr>
            <tr>
              <td>Loss (Frames)</td>
              <td>0</td>
            </tr>
            <tr>
              <td>Loss Rate (Percent)</td>
              <td>0 %</td>
            </tr>

            <!-- divide -->

            <tr>
              <td>P-0-0-2</td>
              <td></td>
            </tr>
            <tr>
              <td>- Tx (Frames)</td>
              <td></td>
            </tr>
            <tr>
              <td>- Tx Rate (L1) (Bit/s)</td>
              <td>500 M</td>
            </tr>
            <tr>
              <td>- Tx Rate (Fps)</td>
              <td>117,481</td>
            </tr>
            <tr>
              <td>- Rx (Frames)</td>
              <td>117,481</td>
            </tr>
            <tr>
              <td>- Rx Rate (L1) (Bit/s)</td>
              <td>500 M</td>
            </tr>
            <tr>
              <td>- Rx Rate (Fps)</td>
              <td>117,481</td>
            </tr>

            <!-- divide -->

            <tr>
              <td>P-0-0-3</td>
              <td></td>
            </tr>
            <tr>
              <td>- Tx (Frames)</td>
              <td></td>
            </tr>
            <tr>
              <td>- Tx Rate (L1) (Bit/s)</td>
              <td>500 M</td>
            </tr>
            <tr>
              <td>- Tx Rate (Fps)</td>
              <td>117,481</td>
            </tr>
            <tr>
              <td>- Rx (Frames)</td>
              <td>117,481</td>
            </tr>
            <tr>
              <td>- Rx Rate (L1) (Bit/s)</td>
              <td>500 M</td>
            </tr>
            <tr>
              <td>- Rx Rate (Fps)</td>
              <td>117,481</td>
            </tr>
          </tbody>
        </table>

        <h4>Results for 100.00% Rate</h4>
        <table class="gridtable">
          <thead>
            <tr>
              <th>Frame Size</th>
              <th>512</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Result State</td>
              <td>PASS</td>
            </tr>
            <tr>
              <td>Tx (Frames)</td>
              <td>234,962</td>
            </tr>
            <tr>
              <td>Tx Rate (Fps)</td>
              <td>234,962</td>
            </tr>
            <tr>
              <td>Tx Rate (L1) (Bit/s)</td>
              <td>1000 M</td>
            </tr>
            <tr>
              <td>Rx (Frames)</td>
              <td>234,962</td>
            </tr>
            <tr>
              <td>Rx Rate (Fps)</td>
              <td>234.96 K</td>
            </tr>
            <tr>
              <td>Rx Rate (L1) (Bit/s)</td>
              <td>1000 M</td>
            </tr>
            <tr>
              <td>Loss (Frames)</td>
              <td>0</td>
            </tr>
            <tr>
              <td>Loss Rate (Percent)</td>
              <td>0 %</td>
            </tr>

            <!-- divide -->

            <tr>
              <td>P-0-0-2</td>
              <td></td>
            </tr>
            <tr>
              <td>- Tx (Frames)</td>
              <td></td>
            </tr>
            <tr>
              <td>- Tx Rate (L1) (Bit/s)</td>
              <td>500 M</td>
            </tr>
            <tr>
              <td>- Tx Rate (Fps)</td>
              <td>117,481</td>
            </tr>
            <tr>
              <td>- Rx (Frames)</td>
              <td>117,481</td>
            </tr>
            <tr>
              <td>- Rx Rate (L1) (Bit/s)</td>
              <td>500 M</td>
            </tr>
            <tr>
              <td>- Rx Rate (Fps)</td>
              <td>117,481</td>
            </tr>

            <!-- divide -->

            <tr>
              <td>P-0-0-3</td>
              <td></td>
            </tr>
            <tr>
              <td>- Tx (Frames)</td>
              <td></td>
            </tr>
            <tr>
              <td>- Tx Rate (L1) (Bit/s)</td>
              <td>500 M</td>
            </tr>
            <tr>
              <td>- Tx Rate (Fps)</td>
              <td>117,481</td>
            </tr>
            <tr>
              <td>- Rx (Frames)</td>
              <td>117,481</td>
            </tr>
            <tr>
              <td>- Rx Rate (L1) (Bit/s)</td>
              <td>500 M</td>
            </tr>
            <tr>
              <td>- Rx Rate (Fps)</td>
              <td>117,481</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <footer>
      <div>Xena Networks - Valkyrie2544 Test Report </div>
      <div >Page <span class="pageCounter"></span>/<span class="totalPages"></span></div>
    </footer>
  </div>
</template>

<style lang="scss" scoped>
table  {page-break-inside: avoid;}
table.gridtable {font-family: verdana,arial,sans-serif;font-size:11px;color:#333333;border-width: 1px;border-color: #666666;border-collapse: collapse;}

table.gridtable th {border-width: 1px;padding: 8px;border-style: solid;border-color: #666666;background-color: #fff;}

table.gridtable td {border-width: 1px;padding: 8px;border-style: solid;border-color: #666666;background-color: #ffffff;}

.report {
  padding: 0 20px;
}

.logo {
  text-align: right;
}

.fields {
  display: flex;
  div {
    &:first-child {
      width: 200px;
    }
  }
}

footer {
  display: flex;
  justify-content: space-between;
}
</style>
